In [82]:
import pandas as pd
import matplotlib.pyplot as plt
import pickle
import seaborn as sns

In [91]:
salary_df = pd.read_csv('proj_data/data_for_salary_prediction.csv')
salary_df.drop(['Unnamed: 0'] ,axis = 1, inplace = True)
salary_df.head(50)

,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors
0,Data Scientist,$53K-$91K (Glassdoor est.),"Data Scientist\nLocation: Albuquerque, NM\nEdu...",3.8,Tecolote Research\n3.8,"Albuquerque, NM","Goleta, CA",501 to 1000 employees,1973,Company - Private,Aerospace & Defense,Aerospace & Defense,$50 to $100 million (USD),-1
1,Healthcare Data Scientist,$63K-$112K (Glassdoor est.),What You Will Do:\n\nI. General Summary\n\nThe...,3.4,University of Maryland Medical System\n3.4,"Linthicum, MD","Baltimore, MD",10000+ employees,1984,Other Organization,Health Care Services & Hospitals,Health Care,$2 to $5 billion (USD),-1
2,Data Scientist,$80K-$90K (Glassdoor est.),"KnowBe4, Inc. is a high growth information sec...",4.8,KnowBe4\n4.8,"Clearwater, FL","Clearwater, FL",501 to 1000 employees,2010,Company - Private,Security Services,Business Services,$100 to $500 million (USD),-1
3,Data Scientist,$56K-$97K (Glassdoor est.),*Organization and Job ID**\nJob ID: 310709\n\n...,3.8,PNNL\n3.8,"Richland, WA","Richland, WA",1001 to 5000 employees,1965,Government,Energy,"Oil, Gas, Energy & Utilities",$500 million to $1 billion (USD),"Oak Ridge National Laboratory, National Renewa..."
4,Data Scientist,$86K-$143K (Glassdoor est.),Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions\n2.9,"New York, NY","New York, NY",51 to 200 employees,1998,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,"Commerce Signals, Cardlytics, Yodlee"
5,Data Scientist,$71K-$119K (Glassdoor est.),CyrusOne is seeking a talented Data Scientist ...,3.4,CyrusOne\n3.4,"Dallas, TX","Dallas, TX",201 to 500 employees,2000,Company - Public,Real Estate,Real Estate,$1 to $2 billion (USD),"Digital Realty, CoreSite, Equinix"
6,Data Scientist,$54K-$93K (Glassdoor est.),Job Description\n\n**Please only local candida...,4.1,ClearOne Advantage\n4.1,"Baltimore, MD","Baltimore, MD",501 to 1000 employees,2008,Company - Private,Banks & Credit Unions,Finance,Unknown / Non-Applicable,-1
7,Data Scientist,$86K-$142K (Glassdoor est.),Advanced Analytics – Lead Data Scientist\nOver...,3.8,Logic20/20\n3.8,"San Jose, CA","Seattle, WA",201 to 500 employees,2005,Company - Private,Consulting,Business Services,$25 to $50 million (USD),-1
8,Research Scientist,$38K-$84K (Glassdoor est.),SUMMARY\n\nThe Research Scientist I will be ta...,3.3,Rochester Regional Health\n3.3,"Rochester, NY","Rochester, NY",10000+ employees,2014,Hospital,Health Care Services & Hospitals,Health Care,$500 million to $1 billion (USD),-1
9,Data Scientist,$120K-$160K (Glassdoor est.),isn’t your usual company. Our work is powered ...,4.6,<intent>\n4.6,"New York, NY","New York, NY",51 to 200 employees,2009,Company - Private,Internet,Information Technology,$100 to $500 million (USD),"Clicktripz, SmarterTravel"
10,Data Scientist,$126K-$201K (Glassdoor est.),"At Wish, our Data Science & Engineering team i...",3.5,Wish\n3.5,"San Jose, CA","San Francisco, CA",501 to 1000 employees,2011,Company - Private,Other Retail Stores,Retail,$1 to $2 billion (USD),-1
11,Data Scientist,$64K-$106K (Glassdoor est.),"Secure our Nation, Ignite your Future\n\nSumma...",4.1,ManTech\n4.1,"Chantilly, VA","Herndon, VA",5001 to 10000 employees,1968,Company - Public,Research & Development,Business Services,$1 to $2 billion (USD),-1
12,Staff Data Scientist - Technology,$106K-$172K (Glassdoor est.),Position Summary...\nDrives the execution of m...,3.2,Walmart\n3.2,"Plano, TX","Bentonville, AR",10000+ employees,1962,Company - Public,"Department, Clothing, & Shoe Stores",Retail,$10+ billion (USD),"Target, Costco Wholesale, Amazon"
13,Data Analyst,$46K-$85K (Glassdoor est.),"Are you an experienced Data Analyst, skilled a...",4.1,Yesler\n4.1,"Seattle, WA","Seattle, WA",201 to 500 employees,2012,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,-1
14,Data Scientist,$83K-$144K (Glassdoor est.),Job Description\n\n\nTakeda is looking for a D...,3.7,Takeda Pharmaceuticals\n3.7,"Cambridge, MA","OSAKA, Japan",10000+ employees,1781,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$10+ billion (USD),"Novartis, Baxter, Pfizer"
15,Data Engineer I,$102K-$190K (Glassdoor est.),This opportunity is within Audibles Data Engin...,3.6,Audible\n3.6,"Newark, NJ","Newark, NJ",1001 to 5000 employees,1995,Subsidiary or Business Segment,Motion Picture Production & Distribution,Media,Unknown / Non-Applicable,-1
16,"Scientist I/II, Biology",$67K-$137K (Glassdoor est.),"Scientist I/II, Biology\n\nCambridge, MA\n\nBI...",3.9,Blueprint Medicines\n3.9,"Cambridge, MA","Cambridge, MA",51 to 200 employees,2011,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$1 to $5 million (USD),"bluebird bio, Agios Pharmaceuticals, Celgene"
17,Customer Data Scientist,$118K-$189K (Glassdoor est.),Company Overview\n\nH2O.ai is the open source ...,4.3,h2o.ai\n4.3,"Mountain View, CA","Mountain View, CA",201 to 500 employees,2011,Company - Private,Enterprise Software & Network Solutions,Information Technology,Unknown / Non-Applicable,-1
18,Data Scientist - Health Data Analytics,$110K-$175K (Glassdoor est.),"At Nuna, our mission is to make high-quality h...",4.2,Nuna\n4.2,"San Francisco, CA","San Francisco, CA",51 to 200 employees,2010,Company - Private,Enterprise Software & Network Solutions,Information Technology,Unknown / Non-Applicable,-1
19,Data Scientist,$64K-$111K (Glassdoor est.),"Pinnacol Assurance does just one thing, and do...",4.0,Pinnacol Assurance\n4.0,"Denver, CO","Denver, CO",501 to 1000 employees,1915,Nonprofit Organization,Insurance Carriers,Insurance,$500 million to $1 billion (USD),-1
20,Data Scientist,$81K-$130K (Glassdoor est.),About Our Team\n\nWe understand that the first...,3.2,Porch\n3.2,"Seattle, WA","Seattle, WA",201 to 500 employees,2012,Company - Private,Internet,Information Technology,Unknown / Non-Applicable,"Angie's List, HomeAdvisor, Thumbtack"
21,Senior Data Scientist / Machine Learning,$73K-$119K (Glassdoor est.),IMMEDIATE NEED FOR A SENIOR DATA SCIENTIST / M...,3.9,Health IQ\n3.9,"Dallas, TX","Mountain View, CA",201 to 500 employees,2013,Company - Private,Insurance Agencies & Brokerages,Insurance,Unknown / Non-Applicable,-1
22,Data Scientist - Quantitative,$86K-$139K (Glassdoor est.),Truckstop.com is hiring a Data Scientist for o...,3.8,Truckstop.com\n3.8,"Chicago, IL","New Plymouth, ID",501 to 1000 employees,1995,Company - Private,Logistics & Supply Chain,Transportation & Logistics,Unknown / Non-Applicable,-1
23,Data Scientist,$63K-$105K (Glassdoor est.),Position Summary\nOur Data Science team is cur...,4.3,SMC 3\n4.3,"Louisville, KY","Peachtree City, GA",51 to 200 employees,1935,Nonprofit Organization,Logistics & Supply Chain,Transportation & Logistics,$10 to $25 million (USD),-1
24,Data Scientist,-1,JOB CATEGORY:\n\nInformation Services\n\nREQUI...,3.9,Mars\n3.9,Oregon,"Mc Lean, VA",10000+ employees,1911,Company - Private,Food & Beverage Manufacturing,Manufacturing,$10+ billion (USD),-1
25,Data Scientist,$109K-$177K (Glassdoor est.),Are you passionate about solving challenging p...,4.0,Novetta\n4.0,"Herndon, VA","Mc Lean, VA",501 to 1000 employees,2012,Company - Private,Enterprise Software & Network Solutions,Information Technology,$100 to $500 million (USD),"Leidos, CACI International, Booz Allen Hamilton"
26,Digital Health Data Scientist,$63K-$110K (Glassdoor est.),ROLE SUMMARY\n\nThe Digital Health Data Scient...,4.0,Pfizer\n4.0,"Cambridge, MA","New York, NY",10000+ employees,1849,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$10+ billion (USD),-1
27,Data Scientist,$75K-$124K (Glassdoor est.),As the Enterprise Data and Analytics Center of...,3.5,First Tech Federal Credit Union\n3.5,"Hillsboro, OR","San Jose, CA",1001 to 5000 employees,1952,Company - Private,Banks & Credit Unions,Finance,$100 to $500 million (USD),-1
28,Associate Data Analyst,$34K-$61K (Glassdoor est.),"Friday, January 17, 2020\n\nOur Enterprise Dat...",3.7,The Hanover Insurance Group\n3.7,"Worcester, MA","Worcester, MA",5001 to 10000 employees,1852,Company - Public,Insurance Carriers,Insurance,$5 to $10 billion (USD),-1
29,Clinical Data Scientist,$63K-$105K (Glassdoor est.),THIS ROLE MUST BE BASED IN SAN DIEGO\n\nAs par...,4.0,Pfizer\n4.0,"Groton, CT","New York, NY",10000+ employees,1849,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$10+ billion (USD),-1
30,Data Scientist,$80K-$90K (Glassdoor est.),"KnowBe4, Inc. is a high growth information sec...",4.8,KnowBe4\n4.8,"Clearwater, FL","Clearwater, FL",501 to 1000 employees,2010,Company - Private,Security Services,Business Services,$100 to $500 million (USD),-1
31,Data Scientist,$56K-$97K (Glassdoor est.),*Organization and Job ID**\nJob ID: 310709\n\n...,3.8,PNNL\n3.8,"Richland, WA","Richland, WA",1001 to 5000 employees,1965,Government,Energy,"Oil, Gas, Energy & Utilities",$500 million to $1 billion (USD),"Oak Ridge National Laboratory, National Renewa..."
32,Data Scientist,$72K-$120K (Glassdoor est.),Preferred Qualifications\nMasters degree or do...,3.6,Amrock\n3.6,"Detroit, MI","Detroit, MI",1001 to 5000 employees,1997,Company - Private,Real Estate,Real Estate,$500 million to $1 billion (USD),-1
33,Data Scientist / Machine Learning Expert,$86K-$143K (Glassdoor est.),Posting Title\nData Scientist / Machine Learni...,3.8,Novartis\n3.8,"Cambridge, MA","Basel, Switzerland",10000+ employees,1996,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$10+ billion (USD),-1
34,Data Scientist,$93K-$149K (Glassdoor est.),"Title: Software Engineer, Data Science\n\nDesi...",3.8,Juniper Networks\n3.8,"Sunnyvale, CA","Sunnyvale, CA",5001 to 10000 employees,1996,Company - Public,Telecommunications Services,Telecommunications,$2 to $5 billion (USD),-1
35,Data Scientist,$85K-$140K (Glassdoor est.),New England Biolabs is seeking a Data Scientis...,4.7,New England Biolabs\n4.7,"Ipswich, MA","Ipswich, MA",201 to 500 employees,1974,Company - Private,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,Unknown / Non-Applicable,"Thermo Fisher Scientific, Enzymatics, Illumina"
36,Web Data Analyst,$77K-$135K (Glassdoor est.),We are looking for a Web Data Analyst to assis...,4.2,Clarity Insights\n4.2,"San Jose, CA","Chicago, IL",201 to 500 employees,2008,Company - Private,IT Services,Information Technology,Unknown / Non-Applicable,-1
37,Data Scientist,$82K-$132K (Glassdoor est.),Overview\n\n\nAre you passionate about changin...,3.5,Esri\n3.5,"Redlands, CA","Redlands, CA",1001 to 5000 employees,1969,Company - Private,Computer Hardware & Software,Information Technology,$1 to $2 billion (USD),Pitney Bowes
38,Data Scientist,$83K-$137K (Glassdoor est.),STR is a government research contractor specia...,4.7,Systems & Technology Research\n4.7,"Woburn, MA","Woburn, MA",201 to 500 employees,2010,Company - Private,Aerospace & Defense,Aerospace & Defense,$100 to $500 million (USD),-1
39,Senior Data Scientist,$115K-$180K (Glassdoor est.),"Sartorius Stedim Data Analytics, a market lead...",3.5,Sartorius\n3.5,"Fremont, CA","Gottingen, Germany",5001 to 10000 employees,1870,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$1 to $2 billion (USD),-1
40,Data Engineer,$74K-$138K (Glassdoor est.),Lancer Insurance Company is looking for a Data...,3.5,Lancer Insurance\n3.5,"Long Beach, NY","Long Beach, NY",201 to 500 employees,1985,Company - Private,Insurance Carriers,Insurance,$100 to $500 million (USD),-1
41,Data Analyst,$64K-$112K (Glassdoor est.),About the Role:\n\nThe Data Analyst plays a cr...,4.2,Sauce Labs\n4.2,"San Francisco, CA","San Francisco, CA",201 to 500 employees,2008,Company - Private,IT Services,Information Technology,$50 to $100 million (USD),"BrowserStack, Selenium Master, Perfecto Mobile"
42,Data Scientist,-1,Take your career to new heights working with a...,4.1,Amount\n4.1,"Chicago, IL","Chicago, IL",201 to 500 employees,2015,Company - Private,Enterprise Software & Network Solutions,Information Technology,Unknown / Non-Applicable,-1
43,Data Engineer,$68K-$129K (Glassdoor est.),Position Title: Data Engineer\n\nPersivia is s...,3.6,Persivia\n3.6,"Marlborough, MA","Lowell, MA",1 to 50 employees,-1,Company - Private,-1,-1,Less than $1 million (USD),-1
44,Data Scientist - Algorithms & Inference,$110K-$175K (Glassdoor est.),"At Nuna, our mission is to make high-quality h...",4.2,Nuna\n4.2,"San Francisco, CA","San Francisco, CA",51 to 200 employees,2010,Company - Private,Enterprise Software & Network Solutions,Information Technology,Unknown / Non-Applicable,-1
45,Scientist,$52K-$113K (Glassdoor est.),"We are a global team of 6000 visionaries, doer...",3.4,Edgewell Personal Care\n3.4,"Allendale, NJ","Shelton, CT",5001 to 10000 employees,2015,Company - Public,Consumer Products Manufacturing,Manufacturing,$2 to $5 billion (USD),"Unilever, Procter & Gamble, Henkel"
46,Senior Data Scientist,$110K-$150K(Employer est.),"Working for Equity Residential (EQR), a leadin...",4.3,Equity Residential\n4.3,"Chicago, IL","Chicago, IL",1001 to 5000 employees,1993,Company - Public,Real Estate,Real Estate,$2 to $5 billion (USD),"UDR, AvalonBay Communities, Essex Property Trust"
47,Data Science Analyst,-1,Company Overview:\n\nBrightside is an employee...,5.0,Brightside\n5.0,"Chandler, AZ","San Francisco, CA",51 to 200 employees,2017,Company - Private,Investment Banking & Asset Management,Finance,Unknown / Non-Applicable,-1
48,Data Scientist,Employer Provided Salary:$150K-$160K,"BPA Services, LLC is seeking a Computer/Data S...",5.0,BPA Services\n5.0,"Washington, DC","Alexandria, VA",Unknown,-1,Company - Private,Enterprise Software & Network Solutions,Information Technology,Unknown / Non-Applicable,-1
49,Lead Data Scientist,$158K-$211K (Glassdoor est.),As the world's leader in digital payments tech...,3.7,Visa Inc.\n3.7,"Bellevue, WA","Foster City, CA",10000+ employees,1958,Company - Public,IT Services,Information Technology,$10+ billion (USD),"American Express, Mastercard, Discover"

# First,we have to clean the Salary estimate

In [84]:
salary_negve = salary_df[salary_df['Salary Estimate'] != '-1']
len(salary_negve)

742

There are 742 instances where '-1' is the salary estimate

#### Now, we have to do some spliting

In [85]:
salary = salary_df['Salary Estimate'].apply(lambda x: x.split('(')[0])
salary

0       $53K-$91K
1      $63K-$112K
2       $80K-$90K
3       $56K-$97K
4      $86K-$143K
          ...
951    $72K-$133K
952     $56K-$91K
953    $95K-$160K
954             -1
955    $61K-$126K
Name: Salary Estimate, Length: 956, dtype: object

##### Remove the K and dollar-sign from the salary-estimate

In [86]:
salary = salary.apply(lambda x: x.replace('K' , '').replace('$' , ''))
salary

0       53-91
1      63-112
2       80-90
3       56-97
4      86-143
        ...
951    72-133
952     56-91
953    95-160
954         -1
955    61-126
Name: Salary Estimate, Length: 956, dtype: object

#### Now, look at the hourly salary

In [87]:
salary_df['Hourly Salary'] = salary_df['Salary Estimate'].apply(lambda x: 1 if 'per hour' in x.lower() else 0)
salary_df.loc[salary_df['Hourly Salary'] == 1].head()

,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,Hourly Salary
197,Medical Lab Scientist,$17-$24 Per Hour(Glassdoor est.),Overview\n\nAbout\n\n\nTower Health is a stron...,3.6,Tower Health\n3.6,"West Reading, PA","Reading, PA",5001 to 10000 employees,2017,Nonprofit Organization,Health Care Services & Hospitals,Health Care,Unknown / Non-Applicable,-1,1
209,MED TECH/LAB SCIENTIST - LABORATORY,$21-$34 Per Hour(Glassdoor est.),Evening: 3P-1130P or Night Shift 11P-730A\n\nI...,3.6,Beebe Healthcare\n3.6,"Lewes, DE","Lewes, DE",1001 to 5000 employees,1935,Nonprofit Organization,Health Care Services & Hospitals,Health Care,$100 to $500 million (USD),-1,1
240,Medical Laboratory Scientist,$18-$25 Per Hour(Glassdoor est.),Description\nMedical Laboratory Scientist - Te...,4.0,Texas Health Huguley Hospital\n4.0,"Burleson, TX","Arlington, TX",1001 to 5000 employees,1977,Hospital,Health Care Services & Hospitals,Health Care,$50 to $100 million (USD),-1,1
247,MED TECH/LAB SCIENTIST- SOUTH COASTAL LAB,$21-$34 Per Hour(Glassdoor est.),Day Shift: 7A-330P. Holidays and every other w...,3.6,Beebe Healthcare\n3.6,"Millville, DE","Lewes, DE",1001 to 5000 employees,1935,Nonprofit Organization,Health Care Services & Hospitals,Health Care,$100 to $500 million (USD),-1,1
257,Medical Technologist / Clinical Laboratory Sci...,$15-$25 Per Hour(Glassdoor est.),The incumbent performs a broad range of labora...,3.4,"Veterans Affairs, Veterans Health Administrati...","New Orleans, LA","Washington, DC",10000+ employees,1930,Government,Federal Agencies,Government,Unknown / Non-Applicable,-1,1

In [88]:
# Remove 'per hour' from the salary estimate
salary_df['Salary Estimate'] = salary_df['Salary Estimate'].apply(lambda x: x.lower().replace('per hour' , ''))
salary_df.head()

,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,Hourly Salary
0,Data Scientist,$53k-$91k (glassdoor est.),"Data Scientist\nLocation: Albuquerque, NM\nEdu...",3.8,Tecolote Research\n3.8,"Albuquerque, NM","Goleta, CA",501 to 1000 employees,1973,Company - Private,Aerospace & Defense,Aerospace & Defense,$50 to $100 million (USD),-1,0
1,Healthcare Data Scientist,$63k-$112k (glassdoor est.),What You Will Do:\n\nI. General Summary\n\nThe...,3.4,University of Maryland Medical System\n3.4,"Linthicum, MD","Baltimore, MD",10000+ employees,1984,Other Organization,Health Care Services & Hospitals,Health Care,$2 to $5 billion (USD),-1,0
2,Data Scientist,$80k-$90k (glassdoor est.),"KnowBe4, Inc. is a high growth information sec...",4.8,KnowBe4\n4.8,"Clearwater, FL","Clearwater, FL",501 to 1000 employees,2010,Company - Private,Security Services,Business Services,$100 to $500 million (USD),-1,0
3,Data Scientist,$56k-$97k (glassdoor est.),*Organization and Job ID**\nJob ID: 310709\n\n...,3.8,PNNL\n3.8,"Richland, WA","Richland, WA",1001 to 5000 employees,1965,Government,Energy,"Oil, Gas, Energy & Utilities",$500 million to $1 billion (USD),"Oak Ridge National Laboratory, National Renewa...",0
4,Data Scientist,$86k-$143k (glassdoor est.),Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions\n2.9,"New York, NY","New York, NY",51 to 200 employees,1998,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,"Commerce Signals, Cardlytics, Yodlee",0

##### There is also some Employer provided salaries, make a column for them

In [89]:
salary_df['Employer_provided_salary'] = salary_df['Salary Estimate'].apply(lambda x : 1 if 'employer provided salary:' in x.lower() else 0)
salary_df.loc[salary_df['Employer_provided_salary'] == 1].head()

,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,Hourly Salary,Employer_provided_salary
48,Data Scientist,employer provided salary:$150k-$160k,"BPA Services, LLC is seeking a Computer/Data S...",5.0,BPA Services\n5.0,"Washington, DC","Alexandria, VA",Unknown,-1,Company - Private,Enterprise Software & Network Solutions,Information Technology,Unknown / Non-Applicable,-1,0,1
161,Data Engineer,employer provided salary:$120k-$145k,"Location: Tampa, FL\nTitle: Data Engineer\nTS/...",5.0,Gridiron IT\n5.0,"Tampa, FL","Reston, VA",51 to 200 employees,2017,Company - Private,IT Services,Information Technology,Unknown / Non-Applicable,-1,0,1
208,Principal Data Scientist with over 10 years ex...,employer provided salary:$200k-$250k,Position Title: Principal Data Scientist\nLoca...,-1.0,CA-One Tech Cloud,"San Francisco, CA","Fremont, CA",51 to 200 employees,2017,Company - Private,IT Services,Information Technology,$5 to $10 million (USD),-1,0,1
331,Principal Data Scientist with over 10 years ex...,employer provided salary:$200k-$250k,Position Title: Principal Data Scientist\nLoca...,-1.0,CA-One Tech Cloud,"San Francisco, CA","Fremont, CA",51 to 200 employees,2017,Company - Private,IT Services,Information Technology,$5 to $10 million (USD),-1,0,1
377,Data Operations Lead,employer provided salary:$85k-$90k,Data Operations Lead\nLocation: Flexible thoug...,-1.0,Muso,"San Francisco, CA","San Francisco, CA",201 to 500 employees,-1,Nonprofit Organization,-1,-1,Unknown / Non-Applicable,-1,0,1

In [93]:
# Remove 'Employer Provided Salary' from the salary Estimate
salary_df['Salary Estimate'] = salary_df['Salary Estimate'].apply(lambda x: x.lower().replace('employer provided salary:' , ''))
salary_df.head(50)

,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors
0,Data Scientist,$53k-$91k (glassdoor est.),"Data Scientist\nLocation: Albuquerque, NM\nEdu...",3.8,Tecolote Research\n3.8,"Albuquerque, NM","Goleta, CA",501 to 1000 employees,1973,Company - Private,Aerospace & Defense,Aerospace & Defense,$50 to $100 million (USD),-1
1,Healthcare Data Scientist,$63k-$112k (glassdoor est.),What You Will Do:\n\nI. General Summary\n\nThe...,3.4,University of Maryland Medical System\n3.4,"Linthicum, MD","Baltimore, MD",10000+ employees,1984,Other Organization,Health Care Services & Hospitals,Health Care,$2 to $5 billion (USD),-1
2,Data Scientist,$80k-$90k (glassdoor est.),"KnowBe4, Inc. is a high growth information sec...",4.8,KnowBe4\n4.8,"Clearwater, FL","Clearwater, FL",501 to 1000 employees,2010,Company - Private,Security Services,Business Services,$100 to $500 million (USD),-1
3,Data Scientist,$56k-$97k (glassdoor est.),*Organization and Job ID**\nJob ID: 310709\n\n...,3.8,PNNL\n3.8,"Richland, WA","Richland, WA",1001 to 5000 employees,1965,Government,Energy,"Oil, Gas, Energy & Utilities",$500 million to $1 billion (USD),"Oak Ridge National Laboratory, National Renewa..."
4,Data Scientist,$86k-$143k (glassdoor est.),Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions\n2.9,"New York, NY","New York, NY",51 to 200 employees,1998,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,"Commerce Signals, Cardlytics, Yodlee"
5,Data Scientist,$71k-$119k (glassdoor est.),CyrusOne is seeking a talented Data Scientist ...,3.4,CyrusOne\n3.4,"Dallas, TX","Dallas, TX",201 to 500 employees,2000,Company - Public,Real Estate,Real Estate,$1 to $2 billion (USD),"Digital Realty, CoreSite, Equinix"
6,Data Scientist,$54k-$93k (glassdoor est.),Job Description\n\n**Please only local candida...,4.1,ClearOne Advantage\n4.1,"Baltimore, MD","Baltimore, MD",501 to 1000 employees,2008,Company - Private,Banks & Credit Unions,Finance,Unknown / Non-Applicable,-1
7,Data Scientist,$86k-$142k (glassdoor est.),Advanced Analytics – Lead Data Scientist\nOver...,3.8,Logic20/20\n3.8,"San Jose, CA","Seattle, WA",201 to 500 employees,2005,Company - Private,Consulting,Business Services,$25 to $50 million (USD),-1
8,Research Scientist,$38k-$84k (glassdoor est.),SUMMARY\n\nThe Research Scientist I will be ta...,3.3,Rochester Regional Health\n3.3,"Rochester, NY","Rochester, NY",10000+ employees,2014,Hospital,Health Care Services & Hospitals,Health Care,$500 million to $1 billion (USD),-1
9,Data Scientist,$120k-$160k (glassdoor est.),isn’t your usual company. Our work is powered ...,4.6,<intent>\n4.6,"New York, NY","New York, NY",51 to 200 employees,2009,Company - Private,Internet,Information Technology,$100 to $500 million (USD),"Clicktripz, SmarterTravel"
10,Data Scientist,$126k-$201k (glassdoor est.),"At Wish, our Data Science & Engineering team i...",3.5,Wish\n3.5,"San Jose, CA","San Francisco, CA",501 to 1000 employees,2011,Company - Private,Other Retail Stores,Retail,$1 to $2 billion (USD),-1
11,Data Scientist,$64k-$106k (glassdoor est.),"Secure our Nation, Ignite your Future\n\nSumma...",4.1,ManTech\n4.1,"Chantilly, VA","Herndon, VA",5001 to 10000 employees,1968,Company - Public,Research & Development,Business Services,$1 to $2 billion (USD),-1
12,Staff Data Scientist - Technology,$106k-$172k (glassdoor est.),Position Summary...\nDrives the execution of m...,3.2,Walmart\n3.2,"Plano, TX","Bentonville, AR",10000+ employees,1962,Company - Public,"Department, Clothing, & Shoe Stores",Retail,$10+ billion (USD),"Target, Costco Wholesale, Amazon"
13,Data Analyst,$46k-$85k (glassdoor est.),"Are you an experienced Data Analyst, skilled a...",4.1,Yesler\n4.1,"Seattle, WA","Seattle, WA",201 to 500 employees,2012,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,-1
14,Data Scientist,$83k-$144k (glassdoor est.),Job Description\n\n\nTakeda is looking for a D...,3.7,Takeda Pharmaceuticals\n3.7,"Cambridge, MA","OSAKA, Japan",10000+ employees,1781,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$10+ billion (USD),"Novartis, Baxter, Pfizer"
15,Data Engineer I,$102k-$190k (glassdoor est.),This opportunity is within Audibles Data Engin...,3.6,Audible\n3.6,"Newark, NJ","Newark, NJ",1001 to 5000 employees,1995,Subsidiary or Business Segment,Motion Picture Production & Distribution,Media,Unknown / Non-Applicable,-1
16,"Scientist I/II, Biology",$67k-$137k (glassdoor est.),"Scientist I/II, Biology\n\nCambridge, MA\n\nBI...",3.9,Blueprint Medicines\n3.9,"Cambridge, MA","Cambridge, MA",51 to 200 employees,2011,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$1 to $5 million (USD),"bluebird bio, Agios Pharmaceuticals, Celgene"
17,Customer Data Scientist,$118k-$189k (glassdoor est.),Company Overview\n\nH2O.ai is the open source ...,4.3,h2o.ai\n4.3,"Mountain View, CA","Mountain View, CA",201 to 500 employees,2011,Company - Private,Enterprise Software & Network Solutions,Information Technology,Unknown / Non-Applicable,-1
18,Data Scientist - Health Data Analytics,$110k-$175k (glassdoor est.),"At Nuna, our mission is to make high-quality h...",4.2,Nuna\n4.2,"San Francisco, CA","San Francisco, CA",51 to 200 employees,2010,Company - Private,Enterprise Software & Network Solutions,Information Technology,Unknown / Non-Applicable,-1
19,Data Scientist,$64k-$111k (glassdoor est.),"Pinnacol Assurance does just one thing, and do...",4.0,Pinnacol Assurance\n4.0,"Denver, CO","Denver, CO",501 to 1000 employees,1915,Nonprofit Organization,Insurance Carriers,Insurance,$500 million to $1 billion (USD),-1
20,Data Scientist,$81k-$130k (glassdoor est.),About Our Team\n\nWe understand that the first...,3.2,Porch\n3.2,"Seattle, WA","Seattle, WA",201 to 500 employees,2012,Company - Private,Internet,Information Technology,Unknown / Non-Applicable,"Angie's List, HomeAdvisor, Thumbtack"
21,Senior Data Scientist / Machine Learning,$73k-$119k (glassdoor est.),IMMEDIATE NEED FOR A SENIOR DATA SCIENTIST / M...,3.9,Health IQ\n3.9,"Dallas, TX","Mountain View, CA",201 to 500 employees,2013,Company - Private,Insurance Agencies & Brokerages,Insurance,Unknown / Non-Applicable,-1
22,Data Scientist - Quantitative,$86k-$139k (glassdoor est.),Truckstop.com is hiring a Data Scientist for o...,3.8,Truckstop.com\n3.8,"Chicago, IL","New Plymouth, ID",501 to 1000 employees,1995,Company - Private,Logistics & Supply Chain,Transportation & Logistics,Unknown / Non-Applicable,-1
23,Data Scientist,$63k-$105k (glassdoor est.),Position Summary\nOur Data Science team is cur...,4.3,SMC 3\n4.3,"Louisville, KY","Peachtree City, GA",51 to 200 employees,1935,Nonprofit Organization,Logistics & Supply Chain,Transportation & Logistics,$10 to $25 million (USD),-1
24,Data Scientist,-1,JOB CATEGORY:\n\nInformation Services\n\nREQUI...,3.9,Mars\n3.9,Oregon,"Mc Lean, VA",10000+ employees,1911,Company - Private,Food & Beverage Manufacturing,Manufacturing,$10+ billion (USD),-1
25,Data Scientist,$109k-$177k (glassdoor est.),Are you passionate about solving challenging p...,4.0,Novetta\n4.0,"Herndon, VA","Mc Lean, VA",501 to 1000 employees,2012,Company - Private,Enterprise Software & Network Solutions,Information Technology,$100 to $500 million (USD),"Leidos, CACI International, Booz Allen Hamilton"
26,Digital Health Data Scientist,$63k-$110k (glassdoor est.),ROLE SUMMARY\n\nThe Digital Health Data Scient...,4.0,Pfizer\n4.0,"Cambridge, MA","New York, NY",10000+ employees,1849,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$10+ billion (USD),-1
27,Data Scientist,$75k-$124k (glassdoor est.),As the Enterprise Data and Analytics Center of...,3.5,First Tech Federal Credit Union\n3.5,"Hillsboro, OR","San Jose, CA",1001 to 5000 employees,1952,Company - Private,Banks & Credit Unions,Finance,$100 to $500 million (USD),-1
28,Associate Data Analyst,$34k-$61k (glassdoor est.),"Friday, January 17, 2020\n\nOur Enterprise Dat...",3.7,The Hanover Insurance Group\n3.7,"Worcester, MA","Worcester, MA",5001 to 10000 employees,1852,Company - Public,Insurance Carriers,Insurance,$5 to $10 billion (USD),-1
29,Clinical Data Scientist,$63k-$105k (glassdoor est.),THIS ROLE MUST BE BASED IN SAN DIEGO\n\nAs par...,4.0,Pfizer\n4.0,"Groton, CT","New York, NY",10000+ employees,1849,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$10+ billion (USD),-1
30,Data Scientist,$80k-$90k (glassdoor est.),"KnowBe4, Inc. is a high growth information sec...",4.8,KnowBe4\n4.8,"Clearwater, FL","Clearwater, FL",501 to 1000 employees,2010,Company - Private,Security Services,Business Services,$100 to $500 million (USD),-1
31,Data Scientist,$56k-$97k (glassdoor est.),*Organization and Job ID**\nJob ID: 310709\n\n...,3.8,PNNL\n3.8,"Richland, WA","Richland, WA",1001 to 5000 employees,1965,Government,Energy,"Oil, Gas, Energy & Utilities",$500 million to $1 billion (USD),"Oak Ridge National Laboratory, National Renewa..."
32,Data Scientist,$72k-$120k (glassdoor est.),Preferred Qualifications\nMasters degree or do...,3.6,Amrock\n3.6,"Detroit, MI","Detroit, MI",1001 to 5000 employees,1997,Company - Private,Real Estate,Real Estate,$500 million to $1 billion (USD),-1
33,Data Scientist / Machine Learning Expert,$86k-$143k (glassdoor est.),Posting Title\nData Scientist / Machine Learni...,3.8,Novartis\n3.8,"Cambridge, MA","Basel, Switzerland",10000+ employees,1996,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$10+ billion (USD),-1
34,Data Scientist,$93k-$149k (glassdoor est.),"Title: Software Engineer, Data Science\n\nDesi...",3.8,Juniper Networks\n3.8,"Sunnyvale, CA","Sunnyvale, CA",5001 to 10000 employees,1996,Company - Public,Telecommunications Services,Telecommunications,$2 to $5 billion (USD),-1
35,Data Scientist,$85k-$140k (glassdoor est.),New England Biolabs is seeking a Data Scientis...,4.7,New England Biolabs\n4.7,"Ipswich, MA","Ipswich, MA",201 to 500 employees,1974,Company - Private,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,Unknown / Non-Applicable,"Thermo Fisher Scientific, Enzymatics, Illumina"
36,Web Data Analyst,$77k-$135k (glassdoor est.),We are looking for a Web Data Analyst to assis...,4.2,Clarity Insights\n4.2,"San Jose, CA","Chicago, IL",201 to 500 employees,2008,Company - Private,IT Services,Information Technology,Unknown / Non-Applicable,-1
37,Data Scientist,$82k-$132k (glassdoor est.),Overview\n\n\nAre you passionate about changin...,3.5,Esri\n3.5,"Redlands, CA","Redlands, CA",1001 to 5000 employees,1969,Company - Private,Computer Hardware & Software,Information Technology,$1 to $2 billion (USD),Pitney Bowes
38,Data Scientist,$83k-$137k (glassdoor est.),STR is a government research contractor specia...,4.7,Systems & Technology Research\n4.7,"Woburn, MA","Woburn, MA",201 to 500 employees,2010,Company - Private,Aerospace & Defense,Aerospace & Defense,$100 to $500 million (USD),-1
39,Senior Data Scientist,$115k-$180k (glassdoor est.),"Sartorius Stedim Data Analytics, a market lead...",3.5,Sartorius\n3.5,"Fremont, CA","Gottingen, Germany",5001 to 10000 employees,1870,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$1 to $2 billion (USD),-1
40,Data Engineer,$74k-$138k (glassdoor est.),Lancer Insurance Company is looking for a Data...,3.5,Lancer Insurance\n3.5,"Long Beach, NY","Long Beach, NY",201 to 500 employees,1985,Company - Private,Insurance Carriers,Insurance,$100 to $500 million (USD),-1
41,Data Analyst,$64k-$112k (glassdoor est.),About the Role:\n\nThe Data Analyst plays a cr...,4.2,Sauce Labs\n4.2,"San Francisco, CA","San Francisco, CA",201 to 500 employees,2008,Company - Private,IT Services,Information Technology,$50 to $100 million (USD),"BrowserStack, Selenium Master, Perfecto Mobile"
42,Data Scientist,-1,Take your career to new heights working with a...,4.1,Amount\n4.1,"Chicago, IL","Chicago, IL",201 to 500 employees,2015,Company - Private,Enterprise Software & Network Solutions,Information Technology,Unknown / Non-Applicable,-1
43,Data Engineer,$68k-$129k (glassdoor est.),Position Title: Data Engineer\n\nPersivia is s...,3.6,Persivia\n3.6,"Marlborough, MA","Lowell, MA",1 to 50 employees,-1,Company - Private,-1,-1,Less than $1 million (USD),-1
44,Data Scientist - Algorithms & Inference,$110k-$175k (glassdoor est.),"At Nuna, our mission is to make high-quality h...",4.2,Nuna\n4.2,"San Francisco, CA","San Francisco, CA",51 to 200 employees,2010,Company - Private,Enterprise Software & Network Solutions,Information Technology,Unknown / Non-Applicable,-1
45,Scientist,$52k-$113k (glassdoor est.),"We are a global team of 6000 visionaries, doer...",3.4,Edgewell Personal Care\n3.4,"Allendale, NJ","Shelton, CT",5001 to 10000 employees,2015,Company - Public,Consumer Products Manufacturing,Manufacturing,$2 to $5 billion (USD),"Unilever, Procter & Gamble, Henkel"
46,Senior Data Scientist,$110k-$150k(employer est.),"Working for Equity Residential (EQR), a leadin...",4.3,Equity Residential\n4.3,"Chicago, IL","Chicago, IL",1001 to 5000 employees,1993,Company - Public,Real Estate,Real Estate,$2 to $5 billion (USD),"UDR, AvalonBay Communities, Essex Property Trust"
47,Data Science Analyst,-1,Company Overview:\n\nBrightside is an employee...,5.0,Brightside\n5.0,"Chandler, AZ","San Francisco, CA",51 to 200 employees,2017,Company - Private,Investment Banking & Asset Management,Finance,Unknown / Non-Applicable,-1
48,Data Scientist,$150k-$160k,"BPA Services, LLC is seeking a Computer/Data S...",5.0,BPA Services\n5.0,"Washington, DC","Alexandria, VA",Unknown,-1,Company - Private,Enterprise Software & Network Solutions,Information Technology,Unknown / Non-Applicable,-1
49,Lead Data Scientist,$158k-$211k (glassdoor est.),As the world's leader in digital payments tech...,3.7,Visa Inc.\n3.7,"Bellevue, WA","Foster City, CA",10000+ employees,1958,Company - Public,IT Services,Information Technology,$10+ billion (USD),"American Express, Mastercard, Discover"

#### Minimum  and Maximum Salary

In [112]:
salary_df['Minimum salary'] = salary.apply(lambda x: int(x.split('-')[0]))
salary_df

ValueError: invalid literal for int() with base 10: ''

In [102]:
salary_df['Minimum salary'].dtype

dtype('O')